name: Fetch VK Data

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch VK Data
      run: |
        curl "https://api.vk.com/method/wall.get?owner_id=174700694&domain=tspk63&offset=1&count=7&access_token=664330a8664330a8664330a8fa6638f9f566643664330a8047988401142e3fe7c189a9a&filter=owner&v=5.236" -o data.json

    - name: Commit data.json to main
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.json
        git commit -m 'Update data.json with new VK data'
        git push origin main

    - name: Checkout gh-pages
      run: |
        git fetch origin
        git checkout gh-pages

    - name: Copy data.json from main to gh-pages
      run: |
        git checkout main -- data.json

    - name: Commit and push to gh-pages
      run: |
        git add data.json
        git commit -m 'Update data.json with new VK data'
        git push origin gh-pages

    - name: Verify data.json content after push
      run: |
        git checkout gh-pages
